services:
  database:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: nokroner_db
      POSTGRES_PORT: "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "nokroner_db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      POSTGRES_DB: nokroner_db
      POSTGRES_HOST: database
      POSTGRES_PORT: "5432"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - pg_admin:/var/lib/pgadmin/

  rails:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails/
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      POSTGRES_DB: nokroner_db
      POSTGRES_HOST: database
      POSTGRES_PORT: "5432"
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./
          target: /rails
        - action: rebuild
          path: Gemfile
        - action: rebuild
          path: ./db/migrate

volumes:
  postgres_data:
  pg_admin: