default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] || "localhost" %>
  port: <%= ENV["POSTGRES_PORT"] || "5432" %>
  username: <%= ENV["POSTGRES_USER"] || "nokroner_db" %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: nokroner_backend_development

test:
  <<: *default
  database: nokroner_backend_test

production:
  primary: &primary_production
    <<: *default
    database: nokroner_backend_production
  cache:
    <<: *primary_production
    database: nokroner_backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: nokroner_backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: nokroner_backend_production_cable
    migrations_paths: db/cable_migrate
